### ISSUE TITLE
read_env() with a different file instead of `.env` doesn't work

### ISSUE THREAD

**Issue by NegassaB** [sloria/environs#302] opened 2023-12-08 17:12 UTC
Hello,
I'm using environs 9.5.0 and I tried to use the `read_env()` with a different file titled `.env.sb` instead of `.env` on django 4.2.1 on my apache 2.4.41 with Ubuntu 20.04.2 server. It's not working, it couldn't read the file. I've put it along side `manage.py` file; doesn't work, I've put it along side `settings.py` file; doesn't work.
When I used `read_env()` with `.env` though it worked.

**Comment by sloria** [comment] 2024-01-10 01:56
I've just tested on environs 9.5.0 and 10.1.0 (latest version) with the following code and was unable to reproduce this issue.

```python
from environs import Env

env = Env()
env.read_env(".env.sb")

FOO = env.str("FOO", required=True)
print(f"{FOO=}")
```

```
FOO=works
```

It's possible that you have an out-of-date version python-dotenv. Can you try updating it to 1.0.0?

Closing for now, will re-open if this remains an issue

**Closed by sloria** 2024-01-10 01:56 UTC

**Comment by NegassaB** [comment] 2024-01-10 07:54
I'm using python-dotenv 1.0.0. Can it an apache problem?

**Comment by sloria** [comment] 2024-01-10 13:35
Hm, if you post a minimal code example that reproduces the issue, that would help to debug this
